### ISSUE TITLE
DB can't be updated after 1.5.3 release

### ISSUE THREAD

**Issue by serhatozkara** [Roomify/RfA#385] opened 2018-04-26 08:31 UTC
DB updates can't be done after 1.5.3 with the following message:

Unresolved dependency | Corresponding Entity References (Version >=3.x required)
-- | --
Roomify Accommodation Booking requires this module and version. Currently using Corresponding Entity References version
Error | Unresolved dependency | Corresponding Entity References (Version >=3.x required)
Roomify Conversations requires this module and version. Currently using Corresponding Entity References version

## Expected Behavior
DB should be updateable.

## Possible Solution
.make files use a git commit version of CER module instead of release or dev versions. Cause the module is built with git version, 3.x dependency is not met.

**Comment by acrollet** [comment] 2018-04-26 12:52
This is a duplicate of #384 and is fixed in master.

**Closed as completed by acrollet** 2018-04-26 12:52 UTC
