### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by VillaCare** [Roomify/RfA#387] opened 2018-05-22 09:48 UTC
When updating a new release things are not functioning as should.

## Expected Behavior
Should function as described in manual

## Current Behavior
When trying to log in as administrator 1st is shows "no secure site" than when entering the User and password the following error pops up: 

<img width="994" alt="screen shot 2018-05-22 at 11 32 49" src="https://user-images.githubusercontent.com/25827314/40354547-6135615c-5db4-11e8-8b05-db0f560330de.png">

Then I return to the user entry and enter the password manually than I enter welcome page. When I want to g to the dash board is shows

<img width="972" alt="screen shot 2018-05-22 at 11 38 14" src="https://user-images.githubusercontent.com/25827314/40354650-aa13ff0a-5db4-11e8-92b1-ab04daad0687.png">

I an access the other 
<img width="365" alt="screen shot 2018-05-22 at 11 39 32" src="https://user-images.githubusercontent.com/25827314/40354726-d3e53790-5db4-11e8-9912-604160fa2690.png">

Than after update it shows: 

<img width="780" alt="screen shot 2018-05-22 at 11 40 36" src="https://user-images.githubusercontent.com/25827314/40354777-f80c3a92-5db4-11e8-81e4-c60c4f876c16.png">

Making a status report it shows 

Info | Drupal | 7.59
-- | -- | --
Info | Install profile | Roomify (roomify-)
OK | Access to update.php | Protected
OK | BAT jQuery Requirements | 1.10
OK | BAT PHP Library | BAT PHP Library installed
OK | Composer Manager | Dependencies installed
Visit the package status page to view the status of individual packages.
OK | Configuration file | Protected
OK | Cron maintenance tasks | Last run 1 hour 13 min ago
You can run cron manually.To run cron from outside the site, go to http://villacare.eu/cron.php?cron_key=fbXsxoMBenNc1SEATy1N7Xhx30lNH6MYV7FQ7Zjoti0
OK | CTools CSS Cache | Exists
OK | cURL | Enabled
Info | Database 4 byte UTF-8 support | Disabled
4 byte UTF-8 for mysql is disabled. See the documentation on adding 4 byte UTF-8 support for more information.
OK | Database system | MySQL, MariaDB, or equivalent
OK | Database system version | 5.5.60-0+deb7u1-log
Error | Database updates | Out of date
Some modules have database schema updates to install. You should run the database update script immediately.
OK | Date API | System date settings
The timezone has been set to UTC. The medium date format type has been set to Tue, 22/05/2018 - 09:42. You may find it helpful to add new format types like Date, Time, Month, or Year, with appropriate formats, at Date and time settings.
OK | Drupal core update status | Up to date
OK | File system | Writable (public download method)
OK | FooTable |  
OK | FullCalendar | FullCalendar, Scheduler and Moment Installed
The FullCalendar, FullCalendar Scheduler and the Moment Library are installed
OK | GD library PNG support | bundled (2.1.0 compatible)
OK | GD library rotate and desaturate effects | bundled (2.1.0 compatible)
Info | GeoPHP and GEOS | GeoPHP library installed and OK. However, GEOS is was not found. While not required, you will see performance improvements if you install the GEOS PHP extension. See the following link for more information.https://github.com/phayes/geoPHP/wiki/GEOS
OK | GeoPHP Library Installed | GeoPHP 1.1 library installed at profiles/roomify/modules/contrib/geophp/geoPHP/geoPHP.inc
Warning | Google Analytics module | Not configured
Google Analytics module has not been configured yet. Please configure its settings from the Google Analytics settings page.
OK | imagesLoaded | 2.1.2
OK | imgAreaSelect | 0.9.11-rc.1
Error | Integration with Google reCAPTCHA service! | Not defined!
Google reCAPTCHA: You must to define public and secret keys to protect Your site from spam. You can do it here >>. Better not to put it off on the later time - spammers are not asleep. Let's make their life harder!! :))
OK | jQuery Images Loaded | 4.1
OK | jQuery Masonry | 4.1.1
OK | jQuery Update | jQuery 1.10.2 (configure) and jQuery UI 1.10.2
OK | Leaflet | 1.0.3+ed36a04
The Leaflet Javascript library is installed correctly. 22 maps available.
Info | Metatag | The Imagecache Token module is recommended.
It is recommended to install the Imagecache Token module to make it easier to control image meta tags, e.g. og:image. See the Metatag module's README.txt for details.
Info | Metatag | The Transliteration module is recommended.
It is recommended to install the Transliteration module to clean up filenames of uploaded files that may be used with image meta tags.
Error | Module and theme update status | Not secure!
There are security updates available for one or more of your modules or themes. To ensure the security of your server, you should update immediately! See the available updates page for more information and to install your missing updates.
Warning | MySQL - max allowed packet | 10 MB
Your MySQL 'max_allowed_packet' setting may be too low for Views data export to function correctly, Drupal's requirements recommend setting it to at least 16M. See: http://drupal.org/requirements
OK | Node Access Permissions | Disabled
If the site is experiencing problems with permissions to content, you may have to rebuild the permissions cache. Rebuilding will remove all privileges to content and replace them with permissions based on the current modules and settings. Rebuilding may take some time if there is a lot of content or complex permission settings. After rebuilding has completed, content will automatically use the new permissions. Rebuild permissions
OK | Panels uuid support. | Available
OK | PHP | 7.0.29 (more information)
OK | PHP extensions | Enabled
OK | PHP memory limit | 256M
OK | PHP register globals | Disabled
OK | RRSSB library | 1.8.1
OK | Selct2 plugin | 4.0.3
OK | Services Authentication Mechanism | Enabled for all Endpoints
Warning | Spyc | The Spyc library could not be found.
OK | Stripe currency check | Valid currency
OK | Stripe PHP library | Installed
OK | Unicode library | PHP Mbstring Extension
OK | Update notifications | Enabled
Info | Upload progress | Not enabled
Your server is capable of displaying file upload progress, but does not have the required libraries. It is recommended to install the PECL uploadprogress library (preferred) or to install APC.
Error | Video transcoder: FFmpeg / avconv |  
Missing the transcoder library. Please install FFmpeg in to your server if you intend to transcode or to auto create thumbnails.
OK | Views Data Export temporary directory | Exists
OK | Web server | Apache
OK | XML sitemap | Last attempted generation on Sun, 20/05/2018 - 17:38 (1 day 16 hours ago).
OK | XML sitemap cache directory | Writable

I use IOS Safari
Hope you can help,

Rgds
.

## Steps to Reproduce from a clean installation of the latest release

1.
2.
3.
4.

**Comment by acrollet** [comment] 2018-05-22 09:58
@villacare please run database updates and consider following the other recommendations on your status report, including the mysql max packet size change.

**Comment by VillaCare** [comment] 2018-05-22 10:59
Hi, when I do that this appears




If you need time / sponsoring to solve this please advise,
Rgds


Ferdinand van Reijsen
VillaCare
HTTP://www.villacare.eu

**Comment by acrollet** [comment] 2018-05-22 11:08
Ah, I see now. This is a Duplicate of #384 and will be solved in the next release. We will try to get a new release out in the next day or two.

**Closed as completed by acrollet** 2018-05-22 11:08 UTC
